name: Deploy ke Niagahoster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 65002
          script: |
            cd /home/u636634107/domains/amplop.site/public_html/
            git reset --hard
            git pull origin main
            composer install --no-dev --optimize-autoloader
            rm -rf node_modules public/build
            npm install
            npm run build
            php artisan migrate --force
            php artisan storage:link
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
